import React from 'react';
import {
  Folder,
  FolderOpen,
  FolderHeart,
  FolderArchive,
  FolderCheck,
  Music,
  Disc,
  Headphones,
  Radio,
  Mic,
  Volume2,
  Sparkles,
  Heart,
  Star,
  Flame,
  Zap,
  Coffee,
  Moon,
  Sun,
  Cloud,
  Compass,
  Bookmark,
  Library,
  Layers,
  Archive,
  Tag,
  BookOpen,
  Feather,
  Smile,
  Activity,
  Award,
  Crown,
  Diamond,
  Gem,
  Key,
  Shield,
  Target,
  Trophy,
  Rocket,
  Plane,
  Globe,
  Palette,
  Camera,
  Film,
  Tv,
  Box,
  Package,
  Cpu,
  Terminal,
  Code,
  Sliders,
  AudioWaveform,
} from 'lucide-react';

export interface FolderIconOption {
  id: string;
  label: string;
  icon: React.ComponentType<{ className?: string }>;
}

export const FOLDER_ICONS: FolderIconOption[] = [
  { id: 'folder', label: 'Default Folder', icon: Folder },
  { id: 'folder-open', label: 'Open Folder', icon: FolderOpen },
  { id: 'folder-heart', label: 'Heart Folder', icon: FolderHeart },
  { id: 'folder-archive', label: 'Archive Folder', icon: FolderArchive },
  { id: 'folder-check', label: 'Check Folder', icon: FolderCheck },
  { id: 'music', label: 'Music Note', icon: Music },
  { id: 'disc', label: 'Vinyl Disc', icon: Disc },
  { id: 'headphones', label: 'Headphones', icon: Headphones },
  { id: 'radio', label: 'Radio', icon: Radio },
  { id: 'mic', label: 'Microphone', icon: Mic },
  { id: 'volume-2', label: 'Volume', icon: Volume2 },
  { id: 'waveform', label: 'Audio Wave', icon: AudioWaveform },
  { id: 'sparkles', label: 'Sparkles', icon: Sparkles },
  { id: 'heart', label: 'Heart', icon: Heart },
  { id: 'star', label: 'Star', icon: Star },
  { id: 'flame', label: 'Flame', icon: Flame },
  { id: 'zap', label: 'Lightning', icon: Zap },
  { id: 'coffee', label: 'Coffee / Chill', icon: Coffee },
  { id: 'moon', label: 'Night / Sleep', icon: Moon },
  { id: 'sun', label: 'Morning / Sun', icon: Sun },
  { id: 'cloud', label: 'Cloud / Ambient', icon: Cloud },
  { id: 'compass', label: 'Explore', icon: Compass },
  { id: 'bookmark', label: 'Bookmark', icon: Bookmark },
  { id: 'library', label: 'Library', icon: Library },
  { id: 'layers', label: 'Layers / Stacks', icon: Layers },
  { id: 'archive', label: 'Archive', icon: Archive },
  { id: 'tag', label: 'Tag / Label', icon: Tag },
  { id: 'book-open', label: 'Book / Audiobooks', icon: BookOpen },
  { id: 'feather', label: 'Acoustic / Feather', icon: Feather },
  { id: 'smile', label: 'Happy / Mood', icon: Smile },
  { id: 'activity', label: 'Workout / Beats', icon: Activity },
  { id: 'award', label: 'Award', icon: Award },
  { id: 'crown', label: 'Crown / VIP', icon: Crown },
  { id: 'diamond', label: 'Diamond', icon: Diamond },
  { id: 'gem', label: 'Rare Gem', icon: Gem },
  { id: 'key', label: 'Master Key', icon: Key },
  { id: 'shield', label: 'Protected', icon: Shield },
  { id: 'target', label: 'Focus / Target', icon: Target },
  { id: 'trophy', label: 'Trophy / Best', icon: Trophy },
  { id: 'rocket', label: 'Energy / Rocket', icon: Rocket },
  { id: 'plane', label: 'Travel / Trip', icon: Plane },
  { id: 'globe', label: 'World / Global', icon: Globe },
  { id: 'palette', label: 'Creative / Art', icon: Palette },
  { id: 'camera', label: 'Visual / Memories', icon: Camera },
  { id: 'film', label: 'Soundtracks / OST', icon: Film },
  { id: 'tv', label: 'Shows / Series', icon: Tv },
  { id: 'box', label: 'Box / Vault', icon: Box },
  { id: 'package', label: 'Collection Pack', icon: Package },
  { id: 'cpu', label: 'Synth / Electronic', icon: Cpu },
  { id: 'terminal', label: 'Coding / Tech', icon: Terminal },
  { id: 'code', label: 'Development', icon: Code },
  { id: 'sliders', label: 'Equalizer / Mix', icon: Sliders },
];

export function getFolderIconComponent(iconId?: string): React.ComponentType<{ className?: string }> {
  if (!iconId) return Folder;
  const match = FOLDER_ICONS.find((item) => item.id === iconId);
  return match ? match.icon : Folder;
}
